name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  TAG: ${{ github.ref_name }}
  IMAGE: cluster-api-addon-provider-fleet
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image
      # - Publish image to ghcr.io
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Push image to ghcr.io
        uses: rancher/ecm-distro-tools/actions/publish-image@da9f5b6e258c327660eeab3db97952b612f1cf9f # v0.69.3
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ env.TAG }}
          platforms: linux/amd64,linux/arm64
          push-to-public: true
          push-to-prime: false
          public-registry: ${{ env.REGISTRY }}
          public-repo: ${{ env.REPOSITORY_OWNER }}
          public-username: ${{ github.actor }}
          public-password: ${{ secrets.GITHUB_TOKEN }}
          make-target: push-image
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    needs: [build]
    steps:
      - name: Install just
        run: cargo install just@1.49.0
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Update manifests
        run: |
          # this is quite naive, but i don't think we need more for now
          sed -i "s/dev/${TAG}/g" config/default/manager_image_patch.yaml
          just release-manifests
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ env.TAG }} --draft --generate-notes metadata.yaml _out/addon-components.yaml
